replicaCount: 2

image:
  repository: <aws-account-id>.dkr.ecr.ap-south-1.amazonaws.com/frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: alb
  host: frontend.example.com

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"

  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

env: {}

podDisruptionBudget:
  enabled: true
  minAvailable: 1