apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: frontend

  namespace: argocd

spec:

  project: 3tier-platform

  source:

    repoURL: https://github.com/Vipraksh23/3tier-platform.git

    targetRevision: main

    path: kubernetes/helm/frontend

  destination:

    server: https://kubernetes.default.svc

    namespace: default

  syncPolicy:

    automated:

      prune: true

      selfHeal: true

    syncOptions:

      - CreateNamespace=true