apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "frontend.fullname" . }}

spec:
  replicas: {{ .Values.replicaCount }}

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: {{ include "frontend.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "frontend.name" . }}

    spec:
      containers:
        - name: frontend

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          resources:
{{ toYaml .Values.resources | indent 12 }}

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}

            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}

            initialDelaySeconds: 10
            periodSeconds: 5

          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true